//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package at.w4cash.signature;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.sales.restaurant.PlaceSplit;
import com.openbravo.pos.util.ModifiedFlowLayout;
import com.openbravo.pos.util.PropertyUtil;

import at.gv.bmf.finanzonline.fon.ws.session.LoginRequest;
import layout.TableLayout;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;

public class WSLoginDialog extends javax.swing.JDialog {

	private AppView m_App;

	/** Creates new form JTicketsBagSharedList */
	private WSLoginDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
	}

	/** Creates new form JTicketsBagSharedList */
	private WSLoginDialog(java.awt.Dialog parent, boolean modal) {
		super(parent, modal);
	}

	public static WSLoginDialog newJDialog(AppView app, Component parentComponent) {
		Window window = getWindow(parentComponent);
		WSLoginDialog mydialog;
		if (window instanceof Frame) {
			mydialog = new WSLoginDialog((Frame) window, true);
		} else {
			mydialog = new WSLoginDialog((Dialog) window, true);
		}

		mydialog.init(app);
		return mydialog;
	}

	private LoginRequest lr = null;
	public LoginRequest showLoginDialog(String tid, String benid, String pin) {
		m_jTID.setText(tid);
		m_jBENID.setText(benid);
		m_jPIN.setText(pin);
		
		setVisible(true);
		return lr;
	}
	
	
	private void init(AppView app) {
		this.m_App = app;
		initComponents();
		
		PropertyUtil.ScaleButtonFontsize(m_App, m_jButtonCancel, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleButtonFontsize(m_App, m_jButtonOK, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleTextFieldFontsize(m_App, m_jTID, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleTextFieldFontsize(m_App, m_jBENID, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleTextFieldFontsize(m_App, m_jPIN, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleLabelFontsize(m_App, jLabelTID, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleLabelFontsize(m_App, jLabelBENID, "common-dialog-fontsize", "22");
		PropertyUtil.ScaleLabelFontsize(m_App, jLabelPIN, "common-dialog-fontsize", "22");
	}

	private static Window getWindow(Component parent) {
		if (parent == null) {
			return new JFrame();
		} else if (parent instanceof Frame || parent instanceof Dialog) {
			return (Window) parent;
		} else {
			return getWindow(parent.getParent());
		}
	}

	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		
		
		m_jdata = new javax.swing.JPanel();
		m_jbuttons = new javax.swing.JPanel();
		m_jButtonCancel = new javax.swing.JButton();
		m_jButtonOK = new javax.swing.JButton();
		m_jTID = new javax.swing.JTextField(); 
		m_jBENID = new javax.swing.JPasswordField();
		m_jPIN = new javax.swing.JPasswordField();
		jLabelTID = new javax.swing.JLabel();
		jLabelBENID = new javax.swing.JLabel();
		jLabelPIN = new javax.swing.JLabel();
		
		
		setAlwaysOnTop(true);
		setTitle(AppLocal.getIntString("caption.WSLogin")); // NOI18N
		setResizable(false);
		setLayout(new java.awt.BorderLayout());
	
		
		m_jdata.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
		
		double size[][] =
            {{TableLayout.PREFERRED, TableLayout.FILL},  // Columns
             {TableLayout.PREFERRED, TableLayout.PREFERRED, TableLayout.PREFERRED}}; // Rows

		m_jdata.setLayout(new TableLayout(size));
		
		jLabelTID.setText(AppLocal.getIntString("wslogin.label.tid"));
		m_jdata.add(jLabelTID, "0, 0");
		m_jdata.add(m_jTID, "1, 0");
		
		jLabelBENID.setText(AppLocal.getIntString("wslogin.label.benid"));
		m_jdata.add(jLabelBENID, "0, 1");
		m_jdata.add(m_jBENID, "1, 1");
		
		jLabelPIN.setText(AppLocal.getIntString("wslogin.label.pin"));
		m_jdata.add(jLabelPIN, "0, 2");
		m_jdata.add(m_jPIN, "1, 2");
		
		getContentPane().add(m_jdata, java.awt.BorderLayout.CENTER);
		
		
		
		m_jbuttons.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
		m_jbuttons.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
		
		
		m_jButtonOK
			.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/button_ok.png"))); // NOI18N
		m_jButtonOK.setText(AppLocal.getIntString("Button.OK")); // NOI18N
		m_jButtonOK.setFocusPainted(false);
		m_jButtonOK.setFocusable(false);
		m_jButtonOK.setMargin(new java.awt.Insets(8, 16, 8, 16));
		m_jButtonOK.setRequestFocusEnabled(false);
		m_jButtonOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				m_jButtonOKActionPerformed(evt);
			}
		});
		
		m_jbuttons.add(m_jButtonOK);
		
		m_jButtonCancel
				.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/button_cancel.png"))); // NOI18N
		m_jButtonCancel.setText(AppLocal.getIntString("Button.Close")); // NOI18N
		m_jButtonCancel.setFocusPainted(false);
		m_jButtonCancel.setFocusable(false);
		m_jButtonCancel.setMargin(new java.awt.Insets(8, 16, 8, 16));
		m_jButtonCancel.setRequestFocusEnabled(false);
		m_jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				m_jButtonCancelActionPerformed(evt);
			}
		});
		
		m_jbuttons.add(m_jButtonCancel);
		
		getContentPane().add(m_jbuttons, java.awt.BorderLayout.SOUTH);
		
		PropertyUtil.ScaleDialog(m_App, this, 768, 480);
	}// </editor-fold>//GEN-END:initComponents

	private void m_jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_m_jButtonCancelActionPerformed
		dispose();
	}// GEN-LAST:event_m_jButtonCancelActionPerformed

	private void m_jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_m_jButtonCancelActionPerformed
		lr = new LoginRequest();
		lr.setTid(m_jTID.getText());
		String benid = new String(m_jBENID.getPassword());
		lr.setBenid(benid);
		String pin = new String(m_jPIN.getPassword()); 
		lr.setPin(pin);
		
		this.setVisible(false);
	}// GEN-LAST:event_m_jButtonCancelActionPerformed
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton m_jButtonCancel;
	private javax.swing.JButton m_jButtonOK;
	private javax.swing.JTextField m_jTID;
	private javax.swing.JPasswordField m_jBENID;
	private javax.swing.JPasswordField m_jPIN;
	private javax.swing.JLabel jLabelTID;
	private javax.swing.JLabel jLabelBENID;
	private javax.swing.JLabel jLabelPIN;
	private javax.swing.JPanel m_jdata;
	private javax.swing.JPanel m_jbuttons;
	// End of variables declaration//GEN-END:variables

}
