//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2007-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.reports;

import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.ClosedCashInfo;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.DataLogicSystem;

import java.awt.Component;
import java.util.Date;
import java.util.List;

import com.openbravo.beans.JCalendarDialog;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.format.Formats;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;

public class JParamsClosedPosInterval extends javax.swing.JPanel implements ReportEditorCreator {

	private static final long serialVersionUID = -4443246826729773270L;
	
	private ComboBoxValModel m_endClosedPosModel;
	private ComboBoxValModel m_startClosedPosModel;
	private AppView m_App;
	
	/** Creates new form JParamsClosedPos */
    public JParamsClosedPosInterval() {
        initComponents();
    }
    
    public void init(AppView app) {
    	m_App = app;
    }

    public void activate() throws BasicException {
    	DataLogicSystem dlSys = (DataLogicSystem) m_App.getBean("com.openbravo.pos.forms.DataLogicSystem");
    	try {
			List<ClosedCashInfo>  closedCashList = dlSys.getAllClosedCashList();
			
			m_endClosedPosModel = new ComboBoxValModel(closedCashList);
			m_endClosedPosModel.setSelectedFirst();
			jcbEndClosedPos.setModel(m_endClosedPosModel);
			
			m_startClosedPosModel = new ComboBoxValModel(closedCashList);
			m_startClosedPosModel.setSelectedFirst();
			jcbStartClosedPos.setModel(m_startClosedPosModel);
			
			
		} catch (BasicException e) {
			// do nothing
		}
    }
    
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[] {Datas.OBJECT, Datas.INT, Datas.OBJECT, Datas.INT});
    }

    public Component getComponent() {
        return this;
    }
    
    public Object createValue() throws BasicException {
        Object startClosedPos = 1; //Formats.TIMESTAMP.parseValue(jTxtStartDate.getText());
        Object endClosedPos = 1; //Formats.TIMESTAMP.parseValue(jTxtEndDate.getText());   
        return new Object[] {
        	m_startClosedPosModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_GREATEROREQUALS,
        	m_startClosedPosModel.getSelectedKey(),
        	m_endClosedPosModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_LESSOREQUALS,
        	m_endClosedPosModel.getSelectedKey()
        };
    }    
    
    public Object getStartItem()
    {
    	return m_startClosedPosModel.getSelectedItem();
    }
    
    public Object getEndItem()
    {
    	return m_endClosedPosModel.getSelectedItem();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbEndClosedPos = new javax.swing.JComboBox<>();
        jcbStartClosedPos = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal.getIntString("label.byclosedpos"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(0, 100));
        setLayout(null);

        jLabel1.setText(AppLocal.getIntString("Label.StartClosedCash")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(20, 20, 120, 16);

        jLabel2.setText(AppLocal.getIntString("Label.EndClosedCash")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 50, 120, 16);

        add(jcbEndClosedPos);
        jcbEndClosedPos.setBounds(130, 50, 310, 22);

        add(jcbStartClosedPos);
        jcbStartClosedPos.setBounds(130, 20, 310, 22);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcbEndClosedPos;
    private javax.swing.JComboBox<String> jcbStartClosedPos;
    // End of variables declaration//GEN-END:variables

	@Override
	public void ScaleButtons() {
		// TODO Auto-generated method stub
		
	}
    
}

