//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2008-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.sales;

import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.pos.util.PropertyUtil;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.List;

import javax.swing.JComboBox;

/**
 *
 * @author adrian
 */
public class JProductAttListItem extends javax.swing.JPanel implements JProductAttEditI {

    private String attid;
    private ComboBoxValModel model;

    /** Creates new form JProductAttListItem */
    public JProductAttListItem(String attid, String label, String value, List<String> values) {

        this.attid = attid;

        initComponents();

        jLabel1.setText(label);

        jValues.addItem(""); // add empty item
        for (String item : values) {
            jValues.addItem(item);
        }
        jValues.setSelectedItem(value);
    }
    
    public double scaleFont(int fontSize)
    {
    	PropertyUtil.ScaleLabelFontsizeAndDimension(jLabel1, fontSize);
    	return PropertyUtil.ScaleComboboxFontSize(jValues, fontSize);
    }
    
    public int getComponentWidth(){
    	return jLabel1.getSize().width + jValues.getSize().width + 10;
    }
    
    public int getComponentHeight()
    {
    	return jLabel1.getHeight();
    }

    public void assignSelection() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jValues.requestFocus();
            }
        });
    }

    public String getAttribute() {
        return attid;
    }

    public String getValue() {
        return (String) jValues.getSelectedItem();
    }

    public Component getComponent() {
        return this;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jValues = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new Dimension(80, jLabel1.getFont().getSize()+5));
        
        this.setLayout(new BorderLayout());
        this.add(jLabel1, BorderLayout.WEST);
        this.add(jValues, BorderLayout.CENTER);
        this.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jValues;
    // End of variables declaration//GEN-END:variables

}
