//    Openbravo POS is a point of sales application designed for touch screens.
//    Copyright (C) 2008-2009 Openbravo, S.L.
//    http://www.openbravo.com/product/pos
//
//    This file is part of Openbravo POS.
//
//    Openbravo POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Openbravo POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.sales;

import com.openbravo.editor.JEditorKeys;
import com.openbravo.pos.util.PropertyUtil;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author adrian
 */
public class JProductAttEditItem extends javax.swing.JPanel implements JProductAttEditI {

    private String attid;

    /** Creates new form JProductAttEditItem */
    public JProductAttEditItem(String attid, String label, String value) {

        this.attid = attid;

        initComponents();

        jLabel1.setText(label);
        jValue.setText(value);
    }
    
    public double scaleFont(int fontSize)
    {
    	double scaleFactor = PropertyUtil.ScaleLabelFontsizeAndDimension(jLabel1, fontSize);
    	PropertyUtil.ScaleTextFieldFontsize(jValue, fontSize);
    	
    	return scaleFactor;
    	
    }
    
    public void assignSelection() {
        jValue.grabFocus();
    }

    public String getAttribute() {
        return attid;
    }

    public String getValue() {
        return jValue.getText();
    }

    public Component getComponent() {
        return this;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jValue = new javax.swing.JTextField(10);

        
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new Dimension(80, jLabel1.getFont().getSize()+5));
        jValue.setFont(jLabel1.getFont());
        jValue.setText("Test Text");
        // jValue.setPreferredSize(new Dimension(220, jLabel1.getFont().getSize()+5));
        
        this.setLayout(new BorderLayout());
        this.add(jLabel1, BorderLayout.WEST);
        this.add(jValue, BorderLayout.CENTER);
        this.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        
       
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jValue;
    // End of variables declaration//GEN-END:variables

}
