--    Openbravo POS is a point of sales application designed for touch screens.
--    Copyright (C) 2010 Openbravo, S.L.
--    http://sourceforge.net/projects/openbravopos
--
--    This file is part of Openbravo POS.
--
--    Openbravo POS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    Openbravo POS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

-- Database upgrade script for ORACLE 2.44.5( -> 2.44.6)


UPDATE APPLICATIONS SET DBServerName = SYS_CONTEXT('USERENV', 'SERVER_HOST');


CREATE TABLE LOGS (
    logTIME TIMESTAMP NOT NULL,
    logHOST VARCHAR2(256) NOT NULL,
    logLEVEL VARCHAR2(16) NOT NULL,
    logMESSAGE VARCHAR2(1024) NOT NULL
);
CREATE INDEX LOGS_TIME ON LOGS(logTIME);


CREATE TABLE SIGNATURES (
    ID VARCHAR2(256) NOT NULL,
    DBSERVERNAME VARCHAR2(256) NOT NULL,
    CERTSERIAL BLOB NOT NULL,
    CERTDERBASE64 BLOB NOT NULL,
    CERTPROVIDERID VARCHAR2(256) NOT NULL,
    ACTIVE INTEGER NOT NULL,
    REGOFFLINE INTEGER,
    OUTAGESINCE TIMESTAMP,
    OUTAGEREGOFFLINE INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE CERTIFICATECHAIN (
    ID VARCHAR2(256) NOT NULL,
    SIGNATUREID VARCHAR2(256) NOT NULL,
    CHAINNO INTEGER NOT NULL,
    CERTDERBASE64 BLOB NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CERTCHAIN_FK_SIGNATUREID FOREIGN KEY (SIGNATUREID) REFERENCES SIGNATURES(ID)
);

ALTER TABLE APPLICATIONS ADD DBSERVERNAME VARCHAR2(256);
ALTER TABLE APPLICATIONS ADD POSID VARCHAR2(256);
ALTER TABLE APPLICATIONS ADD AESBASE64 VARCHAR2(1024);
ALTER TABLE APPLICATIONS DROP PRIMARY KEY;
ALTER TABLE APPLICATIONS ADD CONSTRAINT PK_APPLICATIONS PRIMARY KEY(ID, DBSERVERNAME);

ALTER TABLE TICKETS ADD SIGNATUREID VARCHAR2(256);
ALTER TABLE TICKETS ADD SIGNATUREVALUE BLOB;
ALTER TABLE TICKETS ADD CASHSUMCOUNTER DOUBLE PRECISION;
ALTER TABLE TICKETS ADD CASHTICKETID INTEGER;
ALTER TABLE TICKETS ADD ALGORITHMID INTEGER;
ALTER TABLE TICKETS ADD POSID VARCHAR2(256);
ALTER TABLE TICKETS ADD SIGNATUREOUTOFORDER INTEGER;
ALTER TABLE TICKETS ADD CHAINVALUE BLOB;
ALTER TABLE TICKETS ADD CASHSUMCOUNTERENC BLOB;
ALTER TABLE TICKETS ADD VALIDATION INTEGER;
ALTER TABLE TICKETS ADD MONTH INTEGER;

CREATE INDEX TICKETS_CASHTICKETID ON TICKETS(CASHTICKETID);
DROP INDEX TICKETS_TICKETID;
CREATE INDEX TICKETS_TICKETID ON TICKETS(TICKETID);


ALTER TABLE BRANCH_TICKETS ADD SIGNATUREID VARCHAR2(256);
ALTER TABLE BRANCH_TICKETS ADD SIGNATUREVALUE BLOB;
ALTER TABLE BRANCH_TICKETS ADD CASHSUMCOUNTER DOUBLE PRECISION;
ALTER TABLE BRANCH_TICKETS ADD CASHTICKETID INTEGER;
ALTER TABLE BRANCH_TICKETS ADD ALGORITHMID INTEGER;
ALTER TABLE BRANCH_TICKETS ADD POSID VARCHAR2(256);
ALTER TABLE BRANCH_TICKETS ADD SIGNATUREOUTOFORDER INTEGER;
ALTER TABLE BRANCH_TICKETS ADD CHAINVALUE BLOB;
ALTER TABLE BRANCH_TICKETS ADD CASHSUMCOUNTERENC BLOB;
ALTER TABLE BRANCH_TICKETS ADD VALIDATION INTEGER;
ALTER TABLE BRANCH_TICKETS ADD MONTH INTEGER;

CREATE INDEX BR_TICKETS_CASHTICKETID ON BRANCH_TICKETS(CASHTICKETID);
DROP INDEX BR_TICKETS_TICKETID;
CREATE INDEX BR_TICKETS_TICKETID ON BRANCH_TICKETS(TICKETID);


UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.57mm.xml} WHERE NAME='Printer.TicketPreview.57mm';
UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.80mm.xml} WHERE NAME='Printer.TicketPreview.80mm';
UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.TicketPreview.A4.xml} WHERE NAME='Printer.TicketPreview.A4';
UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.Ticket.57mm.xml} WHERE NAME='Printer.Ticket.57mm';
UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.Ticket.80mm.xml} WHERE NAME='Printer.Ticket.80mm';
UPDATE RESOURCES SET CONTENT= $FILE{/com/openbravo/pos/templates/Printer.Ticket.A4.xml} WHERE NAME='Printer.Ticket.A4';





UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{} AND DBServerName = SYS_CONTEXT('USERENV', 'SERVER_HOST');
UPDATE APPLICATIONS SET NAME = 'w4cashdb', VERSION = '2.44.6' WHERE ID = 'w4cashdb' AND DBServerName = SYS_CONTEXT('USERENV', 'SERVER_HOST');
