--    Openbravo POS is a point of sales application designed for touch screens.
--    Copyright (C) 2010 Openbravo, S.L.
--    http://sourceforge.net/projects/openbravopos
--
--    This file is part of Openbravo POS.
--
--    Openbravo POS is free software: you can redistribute it and/or modify
--    it under the terms of the GNU General Public License as published by
--    the Free Software Foundation, either version 3 of the License, or
--    (at your option) any later version.
--
--    Openbravo POS is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--    GNU General Public License for more details.
--
--    You should have received a copy of the GNU General Public License
--    along with Openbravo POS.  If not, see <http://www.gnu.org/licenses/>.

-- Database upgrade script for ORACLE 2.44.6( -> 2.44.7)

UPDATE STOCKCURRENT A SET UNITS = (SELECT SUM(UNITS) FROM STOCKCURRENT B WHERE B.PRODUCT = A.PRODUCT AND A.LOCATION = B.LOCATION GROUP BY LOCATION, PRODUCT) WHERE A.ATTRIBUTESETINSTANCE_ID IS NULL;
DELETE FROM STOCKCURRENT WHERE ATTRIBUTESETINSTANCE_ID IS NOT NULL;

CREATE TABLE STOCKTACKING (
    ID VARCHAR2(256) NOT NULL,
    DATENEW TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(256) NOT NULL,
    LOCATION VARCHAR2(256) NOT NULL,
    STATUS INT,
    PRIMARY KEY (ID),
    CONSTRAINT ST_LOCATION FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
);

CREATE TABLE STOCKTACKINGITEMS (
    ID VARCHAR2(256) NOT NULL,
    STOCKTACKINGID VARCHAR2(256) NOT NULL,
    PRODUCT VARCHAR2(256) NOT NULL,
    NOMINALSTOCK DOUBLE PRECISION NOT NULL,
    ACTUALSTOCK DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT STI_STID FOREIGN KEY (STOCKTACKINGID) REFERENCES STOCKTACKING(ID),
    CONSTRAINT STI_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID)
);

CREATE TABLE STOCKMOVEMENT (
    ID VARCHAR2(256) NOT NULL,
    DATENEW TIMESTAMP NOT NULL,
    DESCRIPTION VARCHAR2(256) NOT NULL,
    DELIVERYREF VARCHAR2(256) NOT NULL,
    LOCATION VARCHAR2(256) NOT NULL,
    STATUS INT,
    PRIMARY KEY (ID),
    CONSTRAINT SM_LOCATION FOREIGN KEY (LOCATION) REFERENCES LOCATIONS(ID)
);

CREATE TABLE STOCKMOVEMENTITEMS (
    ID VARCHAR2(256) NOT NULL,
    STOCKMOVEMENTID VARCHAR2(256) NOT NULL,
    PRODUCT VARCHAR2(256) NOT NULL,
    PRICEBUY DOUBLE PRECISION,
    AMOUNT DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT SMI_STID FOREIGN KEY (STOCKMOVEMENTID) REFERENCES STOCKMOVEMENT(ID),
    CONSTRAINT SMI_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID)
);

ALTER TABLE STOCKDIARY ADD PRICEBUY DOUBLE PRECISION;
ALTER TABLE STOCKDIARY ADD STOCKTACKINGID VARCHAR2(256);
ALTER TABLE STOCKDIARY ADD STOCKMOVEMENTID VARCHAR2(256);

UPDATE APPLICATIONS SET NAME = $APP_NAME{}, VERSION = $APP_VERSION{} WHERE ID = $APP_ID{} AND DBServerName = SYS_CONTEXT('USERENV', 'SERVER_HOST');
UPDATE APPLICATIONS SET NAME = 'w4cashdb', VERSION = '2.44.7' WHERE ID = 'w4cashdb' AND DBServerName = SYS_CONTEXT('USERENV', 'SERVER_HOST');
